name: Logisticargo.pe
favicon: null
layout_spectrum: 0.98178
typography_spectrum: 0.06566833704710007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fff9e9'
    - '#b0afb5'
    - '#dc9112'
    - '#4c596c'
  brandStrength: 0.06636718893423676
  lightness: 0.49740899610333145
  saturation: 0.24853534647263587
  rhythmicContrast: 0.22572299232706428
purpose: []
